# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
_libgcc_mutex=0.1=conda_forge
_openmp_mutex=4.5=2_gnu
_sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
aesara-theano-fallback=0.1.0=pyhd8ed1ab_0
anyio=3.5.0=py39h06a4308_0
appdirs=1.4.4=pyhd3eb1b0_0
argon2-cffi=21.3.0=pyhd3eb1b0_0
argon2-cffi-bindings=21.2.0=py39h7f8727e_0
arviz=0.11.1=pyhd3eb1b0_0
astropy=5.1=py39h7deecbd_0
astroquery=0.4.6=pypi_0
asttokens=2.0.5=pyhd3eb1b0_0
attrs=22.1.0=py39h06a4308_0
autograd=1.5=pypi_0
babel=2.11.0=py39h06a4308_0
backcall=0.2.0=pyhd3eb1b0_0
beautifulsoup4=4.12.2=py39h06a4308_0
binutils_impl_linux-64=2.39=he00db2b_1
binutils_linux-64=2.39=h5fc0e48_12
blas=1.0=openblas
bleach=4.1.0=pyhd3eb1b0_0
bokeh=3.1.0=pypi_0
bottleneck=1.3.5=py39h7deecbd_0
brotli=1.0.9=h5eee18b_7
brotli-bin=1.0.9=h5eee18b_7
brotlipy=0.7.0=py39h27cfd23_1003
bzip2=1.0.8=h7b6447c_0
c-ares=1.19.0=h5eee18b_0
ca-certificates=2023.01.10=h06a4308_0
certifi=2022.12.7=py39h06a4308_0
cffi=1.15.1=py39h5eee18b_3
cftime=1.6.2=py39h7deecbd_0
charset-normalizer=2.0.4=pyhd3eb1b0_0
comm=0.1.2=py39h06a4308_0
contourpy=1.0.5=py39hdb19cb5_0
corner=2.2.2=pypi_0
cryptography=39.0.1=py39h9ce1e76_0
curl=7.88.1=h5eee18b_0
cycler=0.11.0=pyhd3eb1b0_0
dbus=1.13.18=hb2f20db_0
debugpy=1.5.1=py39h295c915_0
decorator=5.1.1=pyhd3eb1b0_0
defusedxml=0.7.1=pyhd3eb1b0_0
entrypoints=0.4=py39h06a4308_0
executing=0.8.3=pyhd3eb1b0_0
exoplanet=0.5.3=pyhd8ed1ab_1
exoplanet-core=0.1.2=py39h1832856_2
expat=2.4.9=h6a678d5_0
fastprogress=1.0.0=pyhb85f177_0
fbpca=1.0=pypi_0
fontconfig=2.14.1=h4c34cd2_2
fonttools=4.25.0=pyhd3eb1b0_0
freetype=2.12.1=h4a9f257_0
future=0.18.3=pypi_0
gcc_impl_linux-64=10.4.0=h5231bdf_19
gcc_linux-64=10.4.0=h9215b83_12
giflib=5.2.1=h5eee18b_3
glib=2.69.1=he621ea3_2
gst-plugins-base=1.14.1=h6a678d5_1
gstreamer=1.14.1=h5eee18b_1
gxx_impl_linux-64=10.4.0=h5231bdf_19
gxx_linux-64=10.4.0=h6e491c6_12
h5py=3.7.0=py39h737f45e_0
hdf4=4.2.13=h3ca952b_2
hdf5=1.10.6=h3ffc7dd_1
html5lib=1.1=pypi_0
icu=58.2=he6710b0_3
idna=3.4=py39h06a4308_0
importlib-metadata=6.0.0=py39h06a4308_0
importlib_metadata=6.0.0=hd3eb1b0_0
importlib_resources=5.2.0=pyhd3eb1b0_1
ipykernel=6.19.2=py39hb070fc8_0
ipython=8.12.0=py39h06a4308_0
ipython_genutils=0.2.0=pyhd3eb1b0_1
ipywidgets=8.0.4=py39h06a4308_0
jaraco-classes=3.2.3=pypi_0
jedi=0.18.1=py39h06a4308_1
jeepney=0.8.0=pypi_0
jinja2=3.1.2=py39h06a4308_0
joblib=1.2.0=pypi_0
jpeg=9e=h5eee18b_1
json5=0.9.6=pyhd3eb1b0_0
jsonschema=4.17.3=py39h06a4308_0
jupyter=1.0.0=py39h06a4308_8
jupyter_client=8.1.0=py39h06a4308_0
jupyter_console=6.6.3=py39h06a4308_0
jupyter_core=5.3.0=py39h06a4308_0
jupyter_server=1.23.4=py39h06a4308_0
jupyterlab=3.5.3=py39h06a4308_0
jupyterlab_pygments=0.1.2=py_0
jupyterlab_server=2.22.0=py39h06a4308_0
jupyterlab_widgets=3.0.5=py39h06a4308_0
kernel-headers_linux-64=3.10.0=h57e8cba_10
keyring=23.13.1=pypi_0
kiwisolver=1.4.4=py39h6a678d5_0
krb5=1.19.4=h568e23c_0
lcms2=2.12=h3be6417_0
ld_impl_linux-64=2.39=hcc3a1bd_1
lerc=3.0=h295c915_0
libbrotlicommon=1.0.9=h5eee18b_7
libbrotlidec=1.0.9=h5eee18b_7
libbrotlienc=1.0.9=h5eee18b_7
libclang=14.0.6=default_hc6dbbc7_1
libclang13=14.0.6=default_he11475f_1
libcurl=7.88.1=h91b91d3_0
libdeflate=1.17=h5eee18b_0
libedit=3.1.20221030=h5eee18b_0
libev=4.33=h7f8727e_1
libevent=2.1.12=h8f2d780_0
libffi=3.4.2=h6a678d5_6
libgcc-devel_linux-64=10.4.0=hd38fd1e_19
libgcc-ng=12.2.0=h65d4601_19
libgfortran-ng=11.2.0=h00389a5_1
libgfortran5=11.2.0=h1234567_1
libgomp=12.2.0=h65d4601_19
libgpuarray=0.7.6=h7f8727e_1
libllvm14=14.0.6=hdb19cb5_2
libnetcdf=4.8.1=h8322cc2_2
libnghttp2=1.46.0=hce63b2e_0
libopenblas=0.3.21=h043d6bf_0
libpng=1.6.39=h5eee18b_0
libpq=12.9=h16c4e8d_3
libsanitizer=10.4.0=h5246dfb_19
libsodium=1.0.18=h7b6447c_0
libssh2=1.10.0=h8f2d780_0
libstdcxx-devel_linux-64=10.4.0=hd38fd1e_19
libstdcxx-ng=12.2.0=h46fd767_19
libtiff=4.5.0=h6a678d5_2
libuuid=1.41.5=h5eee18b_0
libwebp=1.2.4=h11a3e52_1
libwebp-base=1.2.4=h5eee18b_1
libxcb=1.15=h7f8727e_0
libxkbcommon=1.0.1=h5eee18b_1
libxml2=2.10.3=hcbfbd50_0
libxslt=1.1.37=h2085143_0
libzip=1.8.0=h5cef20c_0
lightkurve=2.4.0=pypi_0
lxml=4.9.2=py39h5eee18b_0
lz4-c=1.9.4=h6a678d5_0
mako=1.2.3=py39h06a4308_0
markupsafe=2.1.1=py39h7f8727e_0
matplotlib=3.7.1=py39h06a4308_1
matplotlib-base=3.7.1=py39h417a72b_1
matplotlib-inline=0.1.6=py39h06a4308_0
memoization=0.4.0=pypi_0
mistune=2.0.4=py39h06a4308_0
more-itertools=9.1.0=pypi_0
munkres=1.1.4=py_0
nbclassic=0.5.5=py39h06a4308_0
nbclient=0.5.13=py39h06a4308_0
nbconvert=7.3.1=pyhd8ed1ab_0
nbconvert-core=7.3.1=pyhd8ed1ab_0
nbconvert-pandoc=7.3.1=pyhd8ed1ab_0
nbformat=5.7.0=py39h06a4308_0
ncurses=6.4=h6a678d5_0
nest-asyncio=1.5.6=py39h06a4308_0
netcdf4=1.6.2=py39h89d13dc_0
notebook=6.5.4=py39h06a4308_0
notebook-shim=0.2.2=py39h06a4308_0
nspr=4.33=h295c915_0
nss=3.74=h0370c37_0
numexpr=2.8.4=py39hd2a5715_0
numpy=1.21.5=py39hf838250_3
numpy-base=1.21.5=py39h1e6e340_3
oktopus=0.1.2=pypi_0
openssl=1.1.1t=h7f8727e_0
packaging=23.0=py39h06a4308_0
pandas=1.5.3=py39h417a72b_0
pandoc=2.12=h06a4308_3
pandocfilters=1.5.0=pyhd3eb1b0_0
parso=0.8.3=pyhd3eb1b0_0
patsy=0.5.3=py39h06a4308_0
pcre=8.45=h295c915_0
pexpect=4.8.0=pyhd3eb1b0_3
pickleshare=0.7.5=pyhd3eb1b0_1003
pillow=9.4.0=py39h6a678d5_0
pip=23.0.1=py39h06a4308_0
platformdirs=2.5.2=py39h06a4308_0
ply=3.11=py39h06a4308_0
pooch=1.4.0=pyhd3eb1b0_0
prometheus_client=0.14.1=py39h06a4308_0
prompt-toolkit=3.0.36=py39h06a4308_0
prompt_toolkit=3.0.36=hd3eb1b0_0
psutil=5.9.0=py39h5eee18b_0
ptyprocess=0.7.0=pyhd3eb1b0_2
pure_eval=0.2.2=pyhd3eb1b0_0
pycparser=2.21=pyhd3eb1b0_0
pyerfa=2.0.0=py39h27cfd23_0
pygments=2.11.2=pyhd3eb1b0_0
pygpu=0.7.6=py39hce1f21e_1
pymc3=3.9.3=pyhd8ed1ab_3
pymc3-ext=0.1.1=pypi_0
pyopenssl=23.0.0=py39h06a4308_0
pyparsing=3.0.9=py39h06a4308_0
pyqt=5.15.7=py39h6a678d5_1
pyqt5-sip=12.11.0=py39h6a678d5_1
pyrsistent=0.18.0=py39heee7806_0
pysocks=1.7.1=py39h06a4308_0
python=3.9.16=h7a1cb2a_2
python-dateutil=2.8.2=pyhd3eb1b0_0
python-fastjsonschema=2.16.2=py39h06a4308_0
python_abi=3.9=2_cp39
pytz=2022.7=py39h06a4308_0
pyvo=1.4.1=pypi_0
pyyaml=6.0=py39h5eee18b_1
pyzmq=23.2.0=py39h6a678d5_0
qt-main=5.15.2=h8373d8f_8
qt-webengine=5.15.9=hbbf29b9_6
qtconsole=5.4.2=py39h06a4308_0
qtpy=2.2.0=py39h06a4308_0
qtwebkit=5.212=h3fafdc1_5
readline=8.2=h5eee18b_0
requests=2.28.1=py39h06a4308_1
scikit-learn=1.2.2=pypi_0
scipy=1.10.1=py39h32ae08f_0
seaborn=0.12.2=py39h06a4308_0
secretstorage=3.3.3=pypi_0
send2trash=1.8.0=pyhd3eb1b0_1
setuptools=66.0.0=py39h06a4308_0
sip=6.6.2=py39h6a678d5_0
six=1.16.0=pyhd3eb1b0_1
sniffio=1.2.0=py39h06a4308_1
soupsieve=2.4=py39h06a4308_0
sqlite=3.41.2=h5eee18b_0
stack_data=0.2.0=pyhd3eb1b0_0
sysroot_linux-64=2.17=h57e8cba_10
terminado=0.17.1=py39h06a4308_0
theano=1.0.5=py39h5a03fae_3
threadpoolctl=3.1.0=pypi_0
tinycss2=1.2.1=py39h06a4308_0
tk=8.6.12=h1ccaba5_0
toml=0.10.2=pyhd3eb1b0_0
tomli=2.0.1=py39h06a4308_0
tornado=6.2=py39h5eee18b_0
tqdm=4.65.0=py39hb070fc8_0
traitlets=5.7.1=py39h06a4308_0
typing-extensions=3.10.0.2=hd3eb1b0_0
typing_extensions=3.10.0.2=pyh06a4308_0
tzdata=2023c=h04d1e81_0
uncertainties=3.1.7=pypi_0
urllib3=1.26.15=py39h06a4308_0
wcwidth=0.2.5=pyhd3eb1b0_0
webencodings=0.5.1=py39h06a4308_1
websocket-client=0.58.0=py39h06a4308_4
wheel=0.38.4=py39h06a4308_0
widgetsnbextension=4.0.5=py39h06a4308_0
xarray=2022.11.0=py39h06a4308_0
xyzservices=2023.2.0=pypi_0
xz=5.2.10=h5eee18b_1
yaml=0.2.5=h7b6447c_0
zeromq=4.3.4=h2531618_0
zipp=3.11.0=py39h06a4308_0
zlib=1.2.13=h5eee18b_0
zstd=1.5.5=hc292b87_0